version: '3.8'

services:
  backend:
    container_name: app-backend
    build: 
      context: ./back-end
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    working_dir: /app-backend
    command: npm run dev
    volumes:
      - ./back-end:/app-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: personal_finance_dev
      DB_PORT: 3306

  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_finance_dev
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: